### ISSUE TITLE
Crash when the first time items couldn't fill the screen

### ISSUE THREAD

**Issue by dss886** [nicolasjafelle/PagingListView#10]
error logs didn't show the line num of the exception

~~~
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
            at android.widget.ListView.dispatchDraw(ListView.java:3307)
            at android.view.View.draw(View.java:15117)
            at android.widget.AbsListView.draw(AbsListView.java:4083)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15117)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15117)
            at android.widget.FrameLayout.draw(FrameLayout.java:592)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2595)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:266)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:272)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:311)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2492)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2337)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1968)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
~~~

**Comment by dss886** [comment]
I solved this...

your example in README.md has a small problem will cause crash.

onLoadMoreItems() is called in PagingListView.onScroll()，which will be called 4-5 times during the view initial. mListView.onFinishLoading(false, null) in it will be called many times too. 

Multi-removing footer will cause the IndexOutOfBoundsException.

Here is my code

~~~
listView.setHasMoreItems(false);
listView.setPagingableListener(new PagingListView.Pagingable() {
    @Override
    public void onLoadMoreItems() {
        if (pagination.getPage_current_count() < pagination.getPage_all_count()) {
            mListView.setHasMoreItems(true);
            new BoardAsyncTask(false).execute(1);
        } 
    }
});
private class BoardAsyncTask extends AsyncTask<Integer, Void, Board> {
        @Override
        protected Board doInBackground(Integer... params) {
            // do some background work
            return board;
        }

        @Override
        protected void onPostExecute(Board tempBoard) {
            super.onPostExecute(tempBoard);
            if (pagination.getPage_current_count() == pagination.getPage_all_count()) {
                mListView.onFinishLoading(false, null);
            }
        }
    }
~~~

**Comment by nicolasjafelle** [comment]
Cool thanks! you gave me no time to check it. Thank you so much!
