### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by sytolk** [nicolasjafelle/PagingListView#19]
I have this exception in Fragment (I use AA framework) after:

``` java
@Background
    void setAdapter() {
        setAdapterUI(RestClient.getInstance().getRegions());
    }

@UiThread
void setAdapterUI(Regions[] regions) {
adapter = new RequestPagingAdapter(mActivity, regions, history);
listView.setAdapter(adapter);
listView.setHasMoreItems(true);  //RequestsHistoryFragment line 83
}
```

```
java.lang.ClassCastException: com.opentaxi.android.adapters.RequestPagingAdapter cannot be cast to android.widget.HeaderViewListAdapter
    at com.paging.listview.PagingListView.setHasMoreItems(PagingListView.java:54)
    at com.opentaxi.android.fragments.RequestsHistoryFragment.setAdapterUI(RequestsHistoryFragment.java:83)
    at com.opentaxi.android.fragments.RequestsHistoryFragment_.access$101(RequestsHistoryFragment_.java:27)
    at com.opentaxi.android.fragments.RequestsHistoryFragment_$4.run(RequestsHistoryFragment_.java:136)
    at android.os.Handler.handleCallback(Handler.java:615)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4747)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by sytolk** [comment]
http://stackoverflow.com/questions/24700588/i-am-using-the-listview-add-remove-footer-for-listview-cross-app-in-android-vers

This exception appears in old APIs I have fix it with change order setHasMoreItems() first next setAdapter(). TODO its need to change the order in sample app too.

``` java
if (!listView.hasMoreItems()) listView.setHasMoreItems(true);
adapter = new RequestPagingAdapter(mActivity, regions, history);
listView.setAdapter(adapter);
```

**Comment by nicolasjafelle** [comment]
Hello! Sorry to not reply you quickly, we had a carnival holidays here in Argentina. So, finally you can fix it?

**Comment by sytolk** [comment]
yes I fix it with change order of:
1. listView.setHasMoreItems(true);
2. listView.setAdapter(adapter);
@nicolasjafelle can you change it in sample app too?

**Comment by nicolasjafelle** [comment]
To be honest I am not following anymore this library, I want to do the same but with RecyclerView, but I will change it in a couple of hours. Thanks!

**Comment by sytolk** [comment]
you can add an other branch with RecyclerView and what is the advantage of RecyclerView ?

**Comment by nicolasjafelle** [comment]
The advantages will be the same as the pros and cons between Listview and RecyclerView, basically more flexibility to draw items with the layout manager and out of the box animations and listeners like swipes. The not so good you have to write more boilerplate code with RecyclerView.
